name: Greetings  

on: [pull_request, issues]  #this is the even, every time pull request created this works

jobs: #groups set of actions which needs to be executed.
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1  #the code is in first -interaction, theres is a pre defined actions on the uses that v1 is the version.
      with:    
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you opening a new issue, Please be patient while we assign this issue'
        pr-message: 'Thanks for PR, will check this PR automatically and pass an merge request'
